homems/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include(("mainapp.urls", "mainapp"), namespace='main')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp import views
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dash'),


    path('role/', views.role, name='role'),
    path('edit_role/', views.EditRoleView.as_view(), name='edit_role'),
    path('list_sysuser/', views.list_sys_user, name='list_sysuser'),
    path('edit_sysuser/', views.EditSysUserView.as_view(), name="edit_sysuser"),

    path('notice/', views.notice, name='notice'),
    path('edit_notice/', views.EditPublicNotice.as_view(), name='edit_notice'),

    path('edit_slide/', views.EditSlideWhowView.as_view()),
    path('list_sildeshow/', views.list_slide_show),
    path('list_houseverify/', views.AuditMessage.as_view()),
    path('list_publicnotice/', views.TPublic.as_view()),
    path('public_show/', views.TPublic.as_view()),

    path('lucky_ticket/', views.list_lucky),
    path('edit_lucky/', views.EditLuckyView.as_view()),

    path('complain/', views.get_complain, name='comp'),
    path('comment/', views.get_comment, name='cmmt'),


]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {#    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />#}
    {#    用于移动端    #}
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Admin{% endblock %}</title>
    {% include 'base/css.html' %}
    {% include 'base/js.html' %}

    {% block css %}

    {% endblock %}

    <style>
        .circle-dot-red {
            display: inline-block;
            width: 10px;
            height: 10px;
            background-color: red;
            border-radius: 50%;
        }
    </style>

</head>
<body class="withvernav">
    <div class="bodywrapper">
        {% include 'base/top.html' %}
        {% include 'base/menu.html' %}

        {% block content %}

        {% endblock %}

        {% block footer %}

        {% endblock %}
    </div><!--bodywrapper-->
    {% block js %}

    {% endblock %}

</body>
</html>

templates/base/css.html
<link rel="stylesheet" href="/s/css/style.default.css" type="text/css" />

<!--[if IE 9]>
    <link rel="stylesheet" media="screen" href="/s/css/style.ie9.css"/>
<![endif]-->
<!--[if IE 8]>
    <link rel="stylesheet" media="screen" href="/s/css/style.ie8.css"/>
<![endif]-->

<style>
    #head_small{
        width: 30px;
        height: 30px;
        border: 2px solid lightgray;
        border-radius: 50%;
    }

     #head_big{
        width: 80px;
        height: 80px;
        border: 2px solid lightgray;
        border-radius: 50%;
    }


</style>

templates/base/js.html
<script type="text/javascript" src="/s/js/plugins/jquery-1.7.min.js"></script>
<script type="text/javascript" src="/s/js/plugins/jquery-ui-1.8.16.custom.min.js"></script>
<script type="text/javascript" src="/s/js/plugins/jquery.cookie.js"></script>
<script type="text/javascript" src="/s/js/plugins/jquery.uniform.min.js"></script>
<script type="text/javascript" src="/s/js/plugins/jquery.flot.min.js"></script>
<script type="text/javascript" src="/s/js/plugins/jquery.flot.resize.min.js"></script>
<script type="text/javascript" src="/s/js/plugins/jquery.slimscroll.js"></script>
<script type="text/javascript" src="/s/js/plugins/jquery.alerts.js"></script>
<script type="text/javascript" src="/s/js/plugins/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="/s/js/plugins/charCount.js"></script>
<script type="text/javascript" src="/s/js/plugins/ui.spinner.min.js"></script>
<script type="text/javascript" src="/s/js/plugins/chosen.jquery.min.js"></script>

<script type="text/javascript" src="/s/js/custom/general.js"></script>


<!--[if lte IE 8]>
<script  src="/s/js/plugins/excanvas.min.js"></script><![endif]-->
<!--[if lt IE 9]>
<script src="/s/js/plugins/css3-mediaqueries.js"></script>
<![endif]-->

templates/base/menu.html
<div class="vernav2 iconmenu">
    <ul>
        {% if request.session.login_user.role_code == 'admin' %}
            {#  超级管理员菜单  #}
            <li><a href="#role_menu" class="editor">系统管理</a>
                <span class="arrow"></span>
                <ul id="role_menu">
                    <li><a href="{% url 'main:role' %}">角色管理</a></li>
                    <li><a href="{% url 'main:list_sysuser' %}">系统用户管理</a></li>
                </ul>
            </li>
            <li><a href="{% url 'main:notice' %}" class="editor">公告管理</a></li>
        {% endif %}
         {% if request.session.login_user.role_code == 'activity' %}
             <li><a href="#role_menu" class="support">活动管理</a>
                <span class="arrow"></span>
                <ul id="role_menu">
                    <li><a href="/list_sildeshow/">轮播图管理</a></li>
                    <li><a href="/lucky_ticket/">代金券管理</a></li>

                </ul>
             <li><a href="/public_show/?public_status=1" class="elements">公告查看</a></li>
             </li>
        {% endif %}

         {% if request.session.login_user.role_code == 'verify' %}
             <li><a href="#role_menu" class="support">审核管理</a>
                <span class="arrow"></span>
                <ul id="role_menu">
                    <li><a href="/list_houseverify/">房屋审核</a></li>
                    <li><a href="/list_publicnotice/">公告审核</a></li>
                </ul>
             <li><a href="/public_show/?public_status=1" class="elements">公告查看</a></li>
             </li>

        {% endif %}


    </ul>
    <a class="togglemenu"></a>
    <br/><br/>
</div><!--leftmenu-->

templates/base/top.html
<div class="topheader">
    <div class="left">
{#        <h1 class="logo">Ama.<span>Admin</span></h1>#}
        <h1 class="logo">熊猫<span>之家</span></h1>
{#        <h1 class="logo"><img src="https://dss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=2850383841,3934216362&fm=26&gp=0.jpg" alt="PANDA"><span>熊猫之家</span></h1>#}
        <span class="slogan">管理系统</span>

        <div class="search">
            <form action="" method="post">
                <input type="text" name="keyword" id="keyword" value="请输入" />
                <button class="submitbutton"></button>
            </form>
        </div><!--search-->

        <br clear="all" />

    </div><!--left-->

    <div class="right">
        <div class="userinfo">
            <img id="head_small" src="{% if  request.session.login_user.head %} /m/{{  request.session.login_user.head }}{% else %}/s/images/thumbs/avatar.png{% endif %}" alt="" />
            <span>{{ request.session.login_user.nick_name }}</span>
        </div><!--userinfo-->

        <div class="userinfodrop">
            <div class="avatar">
            	<a href="">
                    <img id="head_big" src="{% if request.session.login_user.head %}/m/{{ request.session.login_user.head }}{% else %}/s/images/thumbs/avatarbig.png{% endif %}" alt="" />
                </a>
                <div class="changetheme">
                    切换主题: <br />
                    <a class="default"></a>
                    <a class="blueline"></a>
                    <a class="greenline"></a>
                    <a class="contrast"></a>
                    <a class="custombg"></a>
                </div>
            </div><!--avatar-->
            <div class="userdata">
                <h4>{{ request.session.login_user.nick_name }}</h4>
                <span class="email">{{ request.session.login_user.email }}</span>
                <ul>
                    <li><a href="editprofile.html">编辑资料</a></li>
                    <li><a href="accountsettings.html">账号设置</a></li>
                    <li><a href="help.html">帮助</a></li>
                    <li><a href="{% url 'main:logout' %}">退出</a></li>
                </ul>
            </div><!--userdata-->
        </div><!--userinfodrop-->
    </div><!--right-->
</div><!--topheader-->


<div class="header">
    <ul class="headermenu">
        <li class="current"><a href="{% url 'main:dash' %}"><span class="icon icon-flatscreen"></span>首页</a></li>
        {% if request.session.login_user.role_code == 'admin' %}
            <li class="current"><a href="{% url 'main:comp' %}"><span class="icon icon-pencil"></span>投诉处理</a></li>
            <li class="current"><a href="{% url 'main:cmmt' %}"><span class="icon icon-chart"></span>评论管理</a></li>
        {% endif %}


    </ul>

   <div class="headerwidget">
        <div class="earnings">
            <div class="one_half">
                <h4>Today's Earnings</h4>
                <h2>$640.01</h2>
            </div><!--one_half-->
            <div class="one_half last alignright">
                <h4>Current Rate</h4>
                <h2>53%</h2>
            </div><!--one_half last-->
        </div><!--earnings-->
    </div><!--headerwidget-->

</div><!--header-->